services:
  postgres:
    image: postgres:16.3-bookworm
    container_name: postgres
    env_file:
      - .env
    volumes:
      - ../postgres/postgres-data:/var/lib/postgresql/data
    #expose:
    #  - $${POSTGRES_PORT}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped